!!------------------------------------------------------------------------
!!      This file was automatically generated by SPACK.
!!------------------------------------------------------------------------

SUBROUTINE SSH_LU_solve (ns, M, x)

!------------------------------------------------------------------------
!     
!     -- DESCRIPTION 
!     
!     This routine solves M * y = x where M is an LU factorization
!     computed by LU_decompose.
!	  This routine is automatically generated by LU.cpp
!     
!------------------------------------------------------------------------
!     
!     -- INPUT VARIABLES
!     
!	  nesp: matrix row number from the chemical species number
!     M: LU factorization computed by LU_decompose.
!     
!     -- INPUT/OUTPUT VARIABLES
!     
!     x: on entry, the right-hand side of the equation. On exit,
!     the solution of the equation.
!     
!     -- OUTPUT VARIABLES
!     
!------------------------------------------------------------------------
!     
!     -- REMARKS
!     
!------------------------------------------------------------------------
!     
!     -- MODIFICATIONS
!     
!------------------------------------------------------------------------
!     
!     -- AUTHOR(S)
!     
!------------------------------------------------------------------------

IMPLICIT NONE

INTEGER ns
DOUBLE PRECISION M(ns,ns)
DOUBLE PRECISION x(ns)
DOUBLE PRECISION temp


!     Forward substitution.

x(1) = x(1) / M(1, 1)

x(2) = x(2) / M(2, 2)

x(3) = x(3) / M(3, 3)

x(4) = x(4) / M(4, 4)

x(5) = x(5) / M(5, 5)

x(6) = x(6) / M(6, 6)

x(7) = x(7) / M(7, 7)

x(8) = x(8) / M(8, 8)

x(9) = x(9) / M(9, 9)

x(10) = x(10) / M(10, 10)

temp = M(11, 10) * x(10)
x(11) = ( x(11) - temp ) / M(11, 11)

x(12) = x(12) / M(12, 12)

temp = M(13, 12) * x(12)
x(13) = ( x(13) - temp ) / M(13, 13)

temp = M(14, 12) * x(12)
x(14) = ( x(14) - temp ) / M(14, 14)

x(15) = x(15) / M(15, 15)

x(16) = x(16) / M(16, 16)

x(17) = x(17) / M(17, 17)

temp = M(18, 15) * x(15)
x(18) = ( x(18) - temp ) / M(18, 18)

temp = M(19, 16) * x(16)
x(19) = ( x(19) - temp ) / M(19, 19)

temp = M(20, 17) * x(17)
x(20) = ( x(20) - temp ) / M(20, 20)

x(21) = x(21) / M(21, 21)

temp = M(22, 21) * x(21)
x(22) = ( x(22) - temp ) / M(22, 22)

x(23) = x(23) / M(23, 23)

temp = M(24, 23) * x(23)
x(24) = ( x(24) - temp ) / M(24, 24)

temp = M(25, 24) * x(24)
x(25) = ( x(25) - temp ) / M(25, 25)

temp = M(26, 25) * x(25)
x(26) = ( x(26) - temp ) / M(26, 26)

x(27) = x(27) / M(27, 27)

temp = M(28, 27) * x(27)
x(28) = ( x(28) - temp ) / M(28, 28)

temp = M(29, 28) * x(28)
x(29) = ( x(29) - temp ) / M(29, 29)

x(30) = x(30) / M(30, 30)

x(31) = x(31) / M(31, 31)

x(32) = x(32) / M(32, 32)

x(33) = x(33) / M(33, 33)

temp = M(34, 22) * x(22)
x(34) = ( x(34) - temp ) / M(34, 34)

temp = M(35, 34) * x(34)
x(35) = ( x(35) - temp ) / M(35, 35)

temp = M(36, 34) * x(34)
x(36) = ( x(36) - temp ) / M(36, 36)

x(37) = x(37) / M(37, 37)

temp = M(38, 8) * x(8)
temp = temp + M(38, 9) * x(9)
x(38) = ( x(38) - temp ) / M(38, 38)

x(39) = x(39) / M(39, 39)

x(40) = x(40) / M(40, 40)

x(41) = x(41) / M(41, 41)

x(42) = x(42) / M(42, 42)

x(43) = x(43) / M(43, 43)

x(44) = x(44) / M(44, 44)

x(45) = x(45) / M(45, 45)

x(46) = x(46) / M(46, 46)

x(47) = x(47) / M(47, 47)

x(48) = x(48) / M(48, 48)

x(49) = x(49) / M(49, 49)

x(50) = x(50) / M(50, 50)

x(51) = x(51) / M(51, 51)

temp = M(52, 51) * x(51)
x(52) = ( x(52) - temp ) / M(52, 52)

x(53) = x(53) / M(53, 53)

x(54) = x(54) / M(54, 54)

x(55) = x(55) / M(55, 55)

temp = M(56, 51) * x(51)
x(56) = ( x(56) - temp ) / M(56, 56)

x(57) = x(57) / M(57, 57)

x(58) = x(58) / M(58, 58)

x(59) = x(59) / M(59, 59)

x(60) = x(60) / M(60, 60)

x(61) = x(61) / M(61, 61)

x(62) = x(62) / M(62, 62)

temp = M(63, 8) * x(8)
temp = temp + M(63, 9) * x(9)
temp = temp + M(63, 38) * x(38)
x(63) = ( x(63) - temp ) / M(63, 63)

temp = M(64, 38) * x(38)
temp = temp + M(64, 63) * x(63)
x(64) = ( x(64) - temp ) / M(64, 64)

temp = M(65, 9) * x(9)
temp = temp + M(65, 64) * x(64)
x(65) = ( x(65) - temp ) / M(65, 65)

x(66) = x(66) / M(66, 66)

x(67) = x(67) / M(67, 67)

temp = M(68, 67) * x(67)
x(68) = ( x(68) - temp ) / M(68, 68)

temp = M(69, 60) * x(60)
temp = temp + M(69, 67) * x(67)
x(69) = ( x(69) - temp ) / M(69, 69)

temp = M(70, 60) * x(60)
temp = temp + M(70, 67) * x(67)
x(70) = ( x(70) - temp ) / M(70, 70)

temp = M(71, 34) * x(34)
temp = temp + M(71, 67) * x(67)
temp = temp + M(71, 68) * x(68)
x(71) = ( x(71) - temp ) / M(71, 71)

x(72) = x(72) / M(72, 72)

temp = M(73, 63) * x(63)
x(73) = ( x(73) - temp ) / M(73, 73)

x(74) = x(74) / M(74, 74)

temp = M(75, 60) * x(60)
temp = temp + M(75, 67) * x(67)
temp = temp + M(75, 74) * x(74)
x(75) = ( x(75) - temp ) / M(75, 75)

temp = M(76, 30) * x(30)
x(76) = ( x(76) - temp ) / M(76, 76)

temp = M(77, 76) * x(76)
x(77) = ( x(77) - temp ) / M(77, 77)

temp = M(78, 31) * x(31)
x(78) = ( x(78) - temp ) / M(78, 78)

temp = M(79, 78) * x(78)
x(79) = ( x(79) - temp ) / M(79, 79)

x(80) = x(80) / M(80, 80)

x(81) = x(81) / M(81, 81)

x(82) = x(82) / M(82, 82)

x(83) = x(83) / M(83, 83)

temp = M(84, 83) * x(83)
x(84) = ( x(84) - temp ) / M(84, 84)

temp = M(85, 38) * x(38)
temp = temp + M(85, 54) * x(54)
temp = temp + M(85, 60) * x(60)
temp = temp + M(85, 67) * x(67)
temp = temp + M(85, 73) * x(73)
temp = temp + M(85, 74) * x(74)
temp = temp + M(85, 83) * x(83)
temp = temp + M(85, 84) * x(84)
x(85) = ( x(85) - temp ) / M(85, 85)

temp = M(86, 9) * x(9)
temp = temp + M(86, 12) * x(12)
temp = temp + M(86, 54) * x(54)
temp = temp + M(86, 58) * x(58)
temp = temp + M(86, 59) * x(59)
temp = temp + M(86, 60) * x(60)
temp = temp + M(86, 67) * x(67)
temp = temp + M(86, 74) * x(74)
temp = temp + M(86, 83) * x(83)
temp = temp + M(86, 84) * x(84)
temp = temp + M(86, 85) * x(85)
x(86) = ( x(86) - temp ) / M(86, 86)

temp = M(87, 5) * x(5)
temp = temp + M(87, 12) * x(12)
temp = temp + M(87, 54) * x(54)
temp = temp + M(87, 58) * x(58)
temp = temp + M(87, 59) * x(59)
temp = temp + M(87, 60) * x(60)
temp = temp + M(87, 61) * x(61)
temp = temp + M(87, 64) * x(64)
temp = temp + M(87, 67) * x(67)
temp = temp + M(87, 73) * x(73)
temp = temp + M(87, 74) * x(74)
temp = temp + M(87, 80) * x(80)
temp = temp + M(87, 83) * x(83)
temp = temp + M(87, 84) * x(84)
temp = temp + M(87, 85) * x(85)
temp = temp + M(87, 86) * x(86)
x(87) = ( x(87) - temp ) / M(87, 87)

x(88) = x(88) / M(88, 88)

x(89) = x(89) / M(89, 89)

temp = M(90, 8) * x(8)
x(90) = ( x(90) - temp ) / M(90, 90)

temp = M(91, 9) * x(9)
x(91) = ( x(91) - temp ) / M(91, 91)

temp = M(92, 39) * x(39)
temp = temp + M(92, 63) * x(63)
temp = temp + M(92, 73) * x(73)
temp = temp + M(92, 84) * x(84)
temp = temp + M(92, 85) * x(85)
temp = temp + M(92, 86) * x(86)
temp = temp + M(92, 87) * x(87)
x(92) = ( x(92) - temp ) / M(92, 92)

temp = M(93, 58) * x(58)
temp = temp + M(93, 59) * x(59)
temp = temp + M(93, 60) * x(60)
temp = temp + M(93, 64) * x(64)
temp = temp + M(93, 65) * x(65)
temp = temp + M(93, 67) * x(67)
temp = temp + M(93, 73) * x(73)
temp = temp + M(93, 74) * x(74)
temp = temp + M(93, 80) * x(80)
temp = temp + M(93, 83) * x(83)
temp = temp + M(93, 84) * x(84)
temp = temp + M(93, 87) * x(87)
x(93) = ( x(93) - temp ) / M(93, 93)

x(94) = x(94) / M(94, 94)

temp = M(95, 83) * x(83)
x(95) = ( x(95) - temp ) / M(95, 95)

temp = M(96, 57) * x(57)
temp = temp + M(96, 95) * x(95)
x(96) = ( x(96) - temp ) / M(96, 96)

temp = M(97, 32) * x(32)
x(97) = ( x(97) - temp ) / M(97, 97)

temp = M(98, 33) * x(33)
x(98) = ( x(98) - temp ) / M(98, 98)

temp = M(99, 7) * x(7)
temp = temp + M(99, 12) * x(12)
temp = temp + M(99, 54) * x(54)
temp = temp + M(99, 58) * x(58)
temp = temp + M(99, 60) * x(60)
temp = temp + M(99, 67) * x(67)
temp = temp + M(99, 74) * x(74)
temp = temp + M(99, 83) * x(83)
temp = temp + M(99, 86) * x(86)
x(99) = ( x(99) - temp ) / M(99, 99)

temp = M(100, 6) * x(6)
temp = temp + M(100, 52) * x(52)
temp = temp + M(100, 62) * x(62)
temp = temp + M(100, 87) * x(87)
temp = temp + M(100, 94) * x(94)
temp = temp + M(100, 99) * x(99)
x(100) = ( x(100) - temp ) / M(100, 100)

temp = M(101, 5) * x(5)
temp = temp + M(101, 12) * x(12)
temp = temp + M(101, 41) * x(41)
temp = temp + M(101, 51) * x(51)
temp = temp + M(101, 52) * x(52)
temp = temp + M(101, 58) * x(58)
temp = temp + M(101, 59) * x(59)
temp = temp + M(101, 60) * x(60)
temp = temp + M(101, 64) * x(64)
temp = temp + M(101, 67) * x(67)
temp = temp + M(101, 73) * x(73)
temp = temp + M(101, 74) * x(74)
temp = temp + M(101, 80) * x(80)
temp = temp + M(101, 83) * x(83)
temp = temp + M(101, 84) * x(84)
temp = temp + M(101, 85) * x(85)
temp = temp + M(101, 86) * x(86)
temp = temp + M(101, 99) * x(99)
temp = temp + M(101, 100) * x(100)
x(101) = ( x(101) - temp ) / M(101, 101)

temp = M(102, 39) * x(39)
temp = temp + M(102, 53) * x(53)
temp = temp + M(102, 58) * x(58)
temp = temp + M(102, 59) * x(59)
temp = temp + M(102, 60) * x(60)
temp = temp + M(102, 63) * x(63)
temp = temp + M(102, 67) * x(67)
temp = temp + M(102, 73) * x(73)
temp = temp + M(102, 74) * x(74)
temp = temp + M(102, 80) * x(80)
temp = temp + M(102, 83) * x(83)
temp = temp + M(102, 84) * x(84)
temp = temp + M(102, 87) * x(87)
temp = temp + M(102, 92) * x(92)
temp = temp + M(102, 99) * x(99)
temp = temp + M(102, 101) * x(101)
x(102) = ( x(102) - temp ) / M(102, 102)

temp = M(103, 4) * x(4)
temp = temp + M(103, 55) * x(55)
temp = temp + M(103, 58) * x(58)
temp = temp + M(103, 59) * x(59)
temp = temp + M(103, 60) * x(60)
temp = temp + M(103, 67) * x(67)
temp = temp + M(103, 74) * x(74)
temp = temp + M(103, 80) * x(80)
temp = temp + M(103, 83) * x(83)
temp = temp + M(103, 87) * x(87)
temp = temp + M(103, 99) * x(99)
temp = temp + M(103, 101) * x(101)
temp = temp + M(103, 102) * x(102)
x(103) = ( x(103) - temp ) / M(103, 103)

temp = M(104, 4) * x(4)
temp = temp + M(104, 5) * x(5)
temp = temp + M(104, 6) * x(6)
temp = temp + M(104, 7) * x(7)
temp = temp + M(104, 8) * x(8)
temp = temp + M(104, 9) * x(9)
temp = temp + M(104, 10) * x(10)
temp = temp + M(104, 12) * x(12)
temp = temp + M(104, 41) * x(41)
temp = temp + M(104, 49) * x(49)
temp = temp + M(104, 50) * x(50)
temp = temp + M(104, 52) * x(52)
temp = temp + M(104, 53) * x(53)
temp = temp + M(104, 55) * x(55)
temp = temp + M(104, 56) * x(56)
temp = temp + M(104, 58) * x(58)
temp = temp + M(104, 59) * x(59)
temp = temp + M(104, 60) * x(60)
temp = temp + M(104, 61) * x(61)
temp = temp + M(104, 62) * x(62)
temp = temp + M(104, 63) * x(63)
temp = temp + M(104, 64) * x(64)
temp = temp + M(104, 65) * x(65)
temp = temp + M(104, 67) * x(67)
temp = temp + M(104, 73) * x(73)
temp = temp + M(104, 74) * x(74)
temp = temp + M(104, 80) * x(80)
temp = temp + M(104, 83) * x(83)
temp = temp + M(104, 84) * x(84)
temp = temp + M(104, 85) * x(85)
temp = temp + M(104, 86) * x(86)
temp = temp + M(104, 87) * x(87)
temp = temp + M(104, 92) * x(92)
temp = temp + M(104, 93) * x(93)
temp = temp + M(104, 94) * x(94)
temp = temp + M(104, 99) * x(99)
temp = temp + M(104, 100) * x(100)
temp = temp + M(104, 101) * x(101)
temp = temp + M(104, 102) * x(102)
temp = temp + M(104, 103) * x(103)
x(104) = ( x(104) - temp ) / M(104, 104)

temp = M(105, 58) * x(58)
temp = temp + M(105, 59) * x(59)
temp = temp + M(105, 60) * x(60)
temp = temp + M(105, 64) * x(64)
temp = temp + M(105, 67) * x(67)
temp = temp + M(105, 73) * x(73)
temp = temp + M(105, 74) * x(74)
temp = temp + M(105, 80) * x(80)
temp = temp + M(105, 83) * x(83)
temp = temp + M(105, 84) * x(84)
temp = temp + M(105, 102) * x(102)
temp = temp + M(105, 103) * x(103)
temp = temp + M(105, 104) * x(104)
x(105) = ( x(105) - temp ) / M(105, 105)

temp = M(106, 5) * x(5)
temp = temp + M(106, 7) * x(7)
temp = temp + M(106, 49) * x(49)
temp = temp + M(106, 54) * x(54)
temp = temp + M(106, 58) * x(58)
temp = temp + M(106, 59) * x(59)
temp = temp + M(106, 61) * x(61)
temp = temp + M(106, 84) * x(84)
temp = temp + M(106, 85) * x(85)
temp = temp + M(106, 86) * x(86)
temp = temp + M(106, 99) * x(99)
temp = temp + M(106, 100) * x(100)
temp = temp + M(106, 101) * x(101)
temp = temp + M(106, 102) * x(102)
temp = temp + M(106, 103) * x(103)
temp = temp + M(106, 104) * x(104)
temp = temp + M(106, 105) * x(105)
x(106) = ( x(106) - temp ) / M(106, 106)

temp = M(107, 49) * x(49)
temp = temp + M(107, 60) * x(60)
temp = temp + M(107, 67) * x(67)
temp = temp + M(107, 74) * x(74)
temp = temp + M(107, 83) * x(83)
temp = temp + M(107, 84) * x(84)
temp = temp + M(107, 87) * x(87)
temp = temp + M(107, 99) * x(99)
temp = temp + M(107, 102) * x(102)
temp = temp + M(107, 103) * x(103)
temp = temp + M(107, 104) * x(104)
temp = temp + M(107, 105) * x(105)
temp = temp + M(107, 106) * x(106)
x(107) = ( x(107) - temp ) / M(107, 107)

temp = M(108, 38) * x(38)
temp = temp + M(108, 39) * x(39)
temp = temp + M(108, 46) * x(46)
temp = temp + M(108, 49) * x(49)
temp = temp + M(108, 50) * x(50)
temp = temp + M(108, 51) * x(51)
temp = temp + M(108, 53) * x(53)
temp = temp + M(108, 54) * x(54)
temp = temp + M(108, 58) * x(58)
temp = temp + M(108, 59) * x(59)
temp = temp + M(108, 60) * x(60)
temp = temp + M(108, 67) * x(67)
temp = temp + M(108, 73) * x(73)
temp = temp + M(108, 74) * x(74)
temp = temp + M(108, 80) * x(80)
temp = temp + M(108, 83) * x(83)
temp = temp + M(108, 85) * x(85)
temp = temp + M(108, 86) * x(86)
temp = temp + M(108, 92) * x(92)
temp = temp + M(108, 99) * x(99)
temp = temp + M(108, 100) * x(100)
temp = temp + M(108, 101) * x(101)
temp = temp + M(108, 102) * x(102)
temp = temp + M(108, 103) * x(103)
temp = temp + M(108, 104) * x(104)
temp = temp + M(108, 105) * x(105)
temp = temp + M(108, 106) * x(106)
temp = temp + M(108, 107) * x(107)
x(108) = ( x(108) - temp ) / M(108, 108)

temp = M(109, 5) * x(5)
temp = temp + M(109, 7) * x(7)
temp = temp + M(109, 8) * x(8)
temp = temp + M(109, 9) * x(9)
temp = temp + M(109, 12) * x(12)
temp = temp + M(109, 52) * x(52)
temp = temp + M(109, 54) * x(54)
temp = temp + M(109, 58) * x(58)
temp = temp + M(109, 59) * x(59)
temp = temp + M(109, 60) * x(60)
temp = temp + M(109, 61) * x(61)
temp = temp + M(109, 63) * x(63)
temp = temp + M(109, 64) * x(64)
temp = temp + M(109, 65) * x(65)
temp = temp + M(109, 67) * x(67)
temp = temp + M(109, 73) * x(73)
temp = temp + M(109, 74) * x(74)
temp = temp + M(109, 80) * x(80)
temp = temp + M(109, 83) * x(83)
temp = temp + M(109, 84) * x(84)
temp = temp + M(109, 86) * x(86)
temp = temp + M(109, 99) * x(99)
temp = temp + M(109, 100) * x(100)
temp = temp + M(109, 101) * x(101)
temp = temp + M(109, 102) * x(102)
temp = temp + M(109, 103) * x(103)
temp = temp + M(109, 104) * x(104)
temp = temp + M(109, 105) * x(105)
temp = temp + M(109, 106) * x(106)
temp = temp + M(109, 107) * x(107)
temp = temp + M(109, 108) * x(108)
x(109) = ( x(109) - temp ) / M(109, 109)

temp = M(110, 38) * x(38)
temp = temp + M(110, 50) * x(50)
temp = temp + M(110, 51) * x(51)
temp = temp + M(110, 83) * x(83)
temp = temp + M(110, 99) * x(99)
temp = temp + M(110, 100) * x(100)
temp = temp + M(110, 101) * x(101)
temp = temp + M(110, 102) * x(102)
temp = temp + M(110, 103) * x(103)
temp = temp + M(110, 104) * x(104)
temp = temp + M(110, 105) * x(105)
temp = temp + M(110, 106) * x(106)
temp = temp + M(110, 107) * x(107)
temp = temp + M(110, 108) * x(108)
temp = temp + M(110, 109) * x(109)
x(110) = ( x(110) - temp ) / M(110, 110)

temp = M(111, 46) * x(46)
temp = temp + M(111, 62) * x(62)
temp = temp + M(111, 64) * x(64)
temp = temp + M(111, 65) * x(65)
temp = temp + M(111, 73) * x(73)
temp = temp + M(111, 84) * x(84)
temp = temp + M(111, 100) * x(100)
temp = temp + M(111, 101) * x(101)
temp = temp + M(111, 102) * x(102)
temp = temp + M(111, 103) * x(103)
temp = temp + M(111, 104) * x(104)
temp = temp + M(111, 105) * x(105)
temp = temp + M(111, 106) * x(106)
temp = temp + M(111, 107) * x(107)
temp = temp + M(111, 108) * x(108)
temp = temp + M(111, 109) * x(109)
temp = temp + M(111, 110) * x(110)
x(111) = ( x(111) - temp ) / M(111, 111)

temp = M(112, 4) * x(4)
temp = temp + M(112, 5) * x(5)
temp = temp + M(112, 7) * x(7)
temp = temp + M(112, 8) * x(8)
temp = temp + M(112, 9) * x(9)
temp = temp + M(112, 10) * x(10)
temp = temp + M(112, 12) * x(12)
temp = temp + M(112, 38) * x(38)
temp = temp + M(112, 41) * x(41)
temp = temp + M(112, 51) * x(51)
temp = temp + M(112, 52) * x(52)
temp = temp + M(112, 53) * x(53)
temp = temp + M(112, 54) * x(54)
temp = temp + M(112, 55) * x(55)
temp = temp + M(112, 56) * x(56)
temp = temp + M(112, 58) * x(58)
temp = temp + M(112, 59) * x(59)
temp = temp + M(112, 60) * x(60)
temp = temp + M(112, 61) * x(61)
temp = temp + M(112, 63) * x(63)
temp = temp + M(112, 64) * x(64)
temp = temp + M(112, 65) * x(65)
temp = temp + M(112, 67) * x(67)
temp = temp + M(112, 73) * x(73)
temp = temp + M(112, 74) * x(74)
temp = temp + M(112, 80) * x(80)
temp = temp + M(112, 83) * x(83)
temp = temp + M(112, 84) * x(84)
temp = temp + M(112, 85) * x(85)
temp = temp + M(112, 86) * x(86)
temp = temp + M(112, 87) * x(87)
temp = temp + M(112, 93) * x(93)
temp = temp + M(112, 99) * x(99)
temp = temp + M(112, 100) * x(100)
temp = temp + M(112, 101) * x(101)
temp = temp + M(112, 102) * x(102)
temp = temp + M(112, 103) * x(103)
temp = temp + M(112, 104) * x(104)
temp = temp + M(112, 105) * x(105)
temp = temp + M(112, 106) * x(106)
temp = temp + M(112, 107) * x(107)
temp = temp + M(112, 108) * x(108)
temp = temp + M(112, 109) * x(109)
temp = temp + M(112, 110) * x(110)
temp = temp + M(112, 111) * x(111)
x(112) = ( x(112) - temp ) / M(112, 112)


!     Backward substitution.

temp = M(111, 112) * x(112)
x(111) = x(111) - temp

temp = M(110, 111) * x(111)
temp = temp + M(110, 112) * x(112)
x(110) = x(110) - temp

temp = M(109, 110) * x(110)
temp = temp + M(109, 111) * x(111)
temp = temp + M(109, 112) * x(112)
x(109) = x(109) - temp

temp = M(108, 109) * x(109)
temp = temp + M(108, 110) * x(110)
temp = temp + M(108, 111) * x(111)
temp = temp + M(108, 112) * x(112)
x(108) = x(108) - temp

temp = M(107, 108) * x(108)
temp = temp + M(107, 109) * x(109)
temp = temp + M(107, 110) * x(110)
temp = temp + M(107, 111) * x(111)
temp = temp + M(107, 112) * x(112)
x(107) = x(107) - temp

temp = M(106, 107) * x(107)
temp = temp + M(106, 108) * x(108)
temp = temp + M(106, 109) * x(109)
temp = temp + M(106, 110) * x(110)
temp = temp + M(106, 111) * x(111)
temp = temp + M(106, 112) * x(112)
x(106) = x(106) - temp

temp = M(105, 106) * x(106)
temp = temp + M(105, 107) * x(107)
temp = temp + M(105, 108) * x(108)
temp = temp + M(105, 109) * x(109)
temp = temp + M(105, 110) * x(110)
temp = temp + M(105, 111) * x(111)
temp = temp + M(105, 112) * x(112)
x(105) = x(105) - temp

temp = M(104, 105) * x(105)
temp = temp + M(104, 106) * x(106)
temp = temp + M(104, 107) * x(107)
temp = temp + M(104, 108) * x(108)
temp = temp + M(104, 109) * x(109)
temp = temp + M(104, 110) * x(110)
temp = temp + M(104, 111) * x(111)
temp = temp + M(104, 112) * x(112)
x(104) = x(104) - temp

temp = M(103, 104) * x(104)
temp = temp + M(103, 105) * x(105)
temp = temp + M(103, 106) * x(106)
temp = temp + M(103, 107) * x(107)
temp = temp + M(103, 108) * x(108)
temp = temp + M(103, 109) * x(109)
temp = temp + M(103, 110) * x(110)
temp = temp + M(103, 111) * x(111)
temp = temp + M(103, 112) * x(112)
x(103) = x(103) - temp

temp = M(102, 103) * x(103)
temp = temp + M(102, 104) * x(104)
temp = temp + M(102, 105) * x(105)
temp = temp + M(102, 106) * x(106)
temp = temp + M(102, 107) * x(107)
temp = temp + M(102, 108) * x(108)
temp = temp + M(102, 109) * x(109)
temp = temp + M(102, 110) * x(110)
temp = temp + M(102, 111) * x(111)
temp = temp + M(102, 112) * x(112)
x(102) = x(102) - temp

temp = M(101, 102) * x(102)
temp = temp + M(101, 103) * x(103)
temp = temp + M(101, 104) * x(104)
temp = temp + M(101, 105) * x(105)
temp = temp + M(101, 106) * x(106)
temp = temp + M(101, 107) * x(107)
temp = temp + M(101, 108) * x(108)
temp = temp + M(101, 109) * x(109)
temp = temp + M(101, 110) * x(110)
temp = temp + M(101, 111) * x(111)
temp = temp + M(101, 112) * x(112)
x(101) = x(101) - temp

temp = M(100, 101) * x(101)
temp = temp + M(100, 102) * x(102)
temp = temp + M(100, 103) * x(103)
temp = temp + M(100, 104) * x(104)
temp = temp + M(100, 105) * x(105)
temp = temp + M(100, 106) * x(106)
temp = temp + M(100, 107) * x(107)
temp = temp + M(100, 108) * x(108)
temp = temp + M(100, 109) * x(109)
temp = temp + M(100, 110) * x(110)
temp = temp + M(100, 111) * x(111)
temp = temp + M(100, 112) * x(112)
x(100) = x(100) - temp

temp = M(99, 102) * x(102)
temp = temp + M(99, 103) * x(103)
temp = temp + M(99, 104) * x(104)
temp = temp + M(99, 105) * x(105)
temp = temp + M(99, 108) * x(108)
temp = temp + M(99, 109) * x(109)
temp = temp + M(99, 110) * x(110)
temp = temp + M(99, 112) * x(112)
x(99) = x(99) - temp

temp = M(98, 100) * x(100)
temp = temp + M(98, 102) * x(102)
temp = temp + M(98, 104) * x(104)
temp = temp + M(98, 110) * x(110)
temp = temp + M(98, 111) * x(111)
temp = temp + M(98, 112) * x(112)
x(98) = x(98) - temp

temp = M(97, 100) * x(100)
temp = temp + M(97, 102) * x(102)
temp = temp + M(97, 104) * x(104)
temp = temp + M(97, 110) * x(110)
temp = temp + M(97, 111) * x(111)
temp = temp + M(97, 112) * x(112)
x(97) = x(97) - temp

temp = M(96, 100) * x(100)
temp = temp + M(96, 102) * x(102)
temp = temp + M(96, 103) * x(103)
temp = temp + M(96, 104) * x(104)
temp = temp + M(96, 105) * x(105)
temp = temp + M(96, 108) * x(108)
temp = temp + M(96, 110) * x(110)
temp = temp + M(96, 111) * x(111)
temp = temp + M(96, 112) * x(112)
x(96) = x(96) - temp

temp = M(95, 100) * x(100)
temp = temp + M(95, 102) * x(102)
temp = temp + M(95, 103) * x(103)
temp = temp + M(95, 104) * x(104)
temp = temp + M(95, 105) * x(105)
temp = temp + M(95, 108) * x(108)
temp = temp + M(95, 110) * x(110)
temp = temp + M(95, 111) * x(111)
temp = temp + M(95, 112) * x(112)
x(95) = x(95) - temp

temp = M(94, 100) * x(100)
temp = temp + M(94, 104) * x(104)
temp = temp + M(94, 107) * x(107)
temp = temp + M(94, 109) * x(109)
temp = temp + M(94, 111) * x(111)
temp = temp + M(94, 112) * x(112)
x(94) = x(94) - temp

temp = M(93, 99) * x(99)
temp = temp + M(93, 101) * x(101)
temp = temp + M(93, 102) * x(102)
temp = temp + M(93, 103) * x(103)
temp = temp + M(93, 104) * x(104)
temp = temp + M(93, 105) * x(105)
temp = temp + M(93, 106) * x(106)
temp = temp + M(93, 108) * x(108)
temp = temp + M(93, 109) * x(109)
temp = temp + M(93, 110) * x(110)
temp = temp + M(93, 112) * x(112)
x(93) = x(93) - temp

temp = M(92, 99) * x(99)
temp = temp + M(92, 101) * x(101)
temp = temp + M(92, 102) * x(102)
temp = temp + M(92, 103) * x(103)
temp = temp + M(92, 104) * x(104)
temp = temp + M(92, 105) * x(105)
temp = temp + M(92, 106) * x(106)
temp = temp + M(92, 108) * x(108)
temp = temp + M(92, 109) * x(109)
temp = temp + M(92, 110) * x(110)
temp = temp + M(92, 112) * x(112)
x(92) = x(92) - temp

temp = M(91, 100) * x(100)
temp = temp + M(91, 102) * x(102)
temp = temp + M(91, 104) * x(104)
temp = temp + M(91, 110) * x(110)
temp = temp + M(91, 111) * x(111)
temp = temp + M(91, 112) * x(112)
x(91) = x(91) - temp

temp = M(90, 100) * x(100)
temp = temp + M(90, 102) * x(102)
temp = temp + M(90, 104) * x(104)
temp = temp + M(90, 110) * x(110)
temp = temp + M(90, 111) * x(111)
temp = temp + M(90, 112) * x(112)
x(90) = x(90) - temp

temp = M(89, 97) * x(97)
temp = temp + M(89, 98) * x(98)
temp = temp + M(89, 100) * x(100)
temp = temp + M(89, 111) * x(111)
temp = temp + M(89, 112) * x(112)
x(89) = x(89) - temp

temp = M(88, 90) * x(90)
temp = temp + M(88, 91) * x(91)
temp = temp + M(88, 100) * x(100)
temp = temp + M(88, 111) * x(111)
temp = temp + M(88, 112) * x(112)
x(88) = x(88) - temp

temp = M(87, 99) * x(99)
temp = temp + M(87, 102) * x(102)
temp = temp + M(87, 103) * x(103)
temp = temp + M(87, 104) * x(104)
temp = temp + M(87, 105) * x(105)
temp = temp + M(87, 108) * x(108)
temp = temp + M(87, 109) * x(109)
temp = temp + M(87, 110) * x(110)
temp = temp + M(87, 112) * x(112)
x(87) = x(87) - temp

temp = M(86, 99) * x(99)
temp = temp + M(86, 102) * x(102)
temp = temp + M(86, 103) * x(103)
temp = temp + M(86, 104) * x(104)
temp = temp + M(86, 105) * x(105)
temp = temp + M(86, 108) * x(108)
temp = temp + M(86, 110) * x(110)
temp = temp + M(86, 112) * x(112)
x(86) = x(86) - temp

temp = M(85, 86) * x(86)
temp = temp + M(85, 99) * x(99)
temp = temp + M(85, 102) * x(102)
temp = temp + M(85, 103) * x(103)
temp = temp + M(85, 104) * x(104)
temp = temp + M(85, 105) * x(105)
temp = temp + M(85, 108) * x(108)
temp = temp + M(85, 110) * x(110)
temp = temp + M(85, 112) * x(112)
x(85) = x(85) - temp

temp = M(84, 102) * x(102)
temp = temp + M(84, 103) * x(103)
temp = temp + M(84, 104) * x(104)
temp = temp + M(84, 105) * x(105)
temp = temp + M(84, 108) * x(108)
x(84) = x(84) - temp

temp = M(83, 102) * x(102)
temp = temp + M(83, 103) * x(103)
temp = temp + M(83, 104) * x(104)
temp = temp + M(83, 105) * x(105)
temp = temp + M(83, 108) * x(108)
x(83) = x(83) - temp

temp = M(82, 83) * x(83)
temp = temp + M(82, 95) * x(95)
temp = temp + M(82, 102) * x(102)
temp = temp + M(82, 104) * x(104)
temp = temp + M(82, 110) * x(110)
x(82) = x(82) - temp

temp = M(81, 97) * x(97)
temp = temp + M(81, 98) * x(98)
temp = temp + M(81, 102) * x(102)
temp = temp + M(81, 110) * x(110)
x(81) = x(81) - temp

temp = M(80, 102) * x(102)
temp = temp + M(80, 103) * x(103)
temp = temp + M(80, 104) * x(104)
temp = temp + M(80, 105) * x(105)
x(80) = x(80) - temp

temp = M(79, 102) * x(102)
temp = temp + M(79, 104) * x(104)
temp = temp + M(79, 110) * x(110)
temp = temp + M(79, 112) * x(112)
x(79) = x(79) - temp

temp = M(78, 102) * x(102)
temp = temp + M(78, 104) * x(104)
temp = temp + M(78, 110) * x(110)
temp = temp + M(78, 112) * x(112)
x(78) = x(78) - temp

temp = M(77, 102) * x(102)
temp = temp + M(77, 104) * x(104)
temp = temp + M(77, 110) * x(110)
temp = temp + M(77, 112) * x(112)
x(77) = x(77) - temp

temp = M(76, 102) * x(102)
temp = temp + M(76, 104) * x(104)
temp = temp + M(76, 110) * x(110)
temp = temp + M(76, 112) * x(112)
x(76) = x(76) - temp

temp = M(75, 102) * x(102)
temp = temp + M(75, 103) * x(103)
temp = temp + M(75, 104) * x(104)
temp = temp + M(75, 105) * x(105)
x(75) = x(75) - temp

temp = M(74, 102) * x(102)
temp = temp + M(74, 103) * x(103)
temp = temp + M(74, 104) * x(104)
temp = temp + M(74, 105) * x(105)
x(74) = x(74) - temp

temp = M(73, 102) * x(102)
temp = temp + M(73, 104) * x(104)
temp = temp + M(73, 108) * x(108)
temp = temp + M(73, 110) * x(110)
temp = temp + M(73, 112) * x(112)
x(73) = x(73) - temp

temp = M(72, 90) * x(90)
temp = temp + M(72, 91) * x(91)
temp = temp + M(72, 102) * x(102)
temp = temp + M(72, 110) * x(110)
x(72) = x(72) - temp

temp = M(71, 74) * x(74)
temp = temp + M(71, 102) * x(102)
temp = temp + M(71, 103) * x(103)
temp = temp + M(71, 104) * x(104)
temp = temp + M(71, 105) * x(105)
temp = temp + M(71, 110) * x(110)
temp = temp + M(71, 112) * x(112)
x(71) = x(71) - temp

temp = M(70, 74) * x(74)
temp = temp + M(70, 102) * x(102)
temp = temp + M(70, 103) * x(103)
temp = temp + M(70, 104) * x(104)
temp = temp + M(70, 105) * x(105)
x(70) = x(70) - temp

temp = M(69, 74) * x(74)
temp = temp + M(69, 102) * x(102)
temp = temp + M(69, 103) * x(103)
temp = temp + M(69, 104) * x(104)
temp = temp + M(69, 105) * x(105)
x(69) = x(69) - temp

temp = M(68, 71) * x(71)
temp = temp + M(68, 74) * x(74)
temp = temp + M(68, 102) * x(102)
temp = temp + M(68, 103) * x(103)
temp = temp + M(68, 104) * x(104)
temp = temp + M(68, 105) * x(105)
x(68) = x(68) - temp

temp = M(67, 102) * x(102)
temp = temp + M(67, 103) * x(103)
temp = temp + M(67, 104) * x(104)
temp = temp + M(67, 105) * x(105)
x(67) = x(67) - temp

temp = M(66, 90) * x(90)
temp = temp + M(66, 91) * x(91)
temp = temp + M(66, 102) * x(102)
temp = temp + M(66, 110) * x(110)
x(66) = x(66) - temp

temp = M(65, 73) * x(73)
temp = temp + M(65, 84) * x(84)
temp = temp + M(65, 102) * x(102)
temp = temp + M(65, 104) * x(104)
temp = temp + M(65, 105) * x(105)
temp = temp + M(65, 110) * x(110)
temp = temp + M(65, 112) * x(112)
x(65) = x(65) - temp

temp = M(64, 73) * x(73)
temp = temp + M(64, 102) * x(102)
temp = temp + M(64, 104) * x(104)
temp = temp + M(64, 105) * x(105)
temp = temp + M(64, 110) * x(110)
temp = temp + M(64, 112) * x(112)
x(64) = x(64) - temp

temp = M(63, 73) * x(73)
temp = temp + M(63, 102) * x(102)
temp = temp + M(63, 104) * x(104)
temp = temp + M(63, 110) * x(110)
temp = temp + M(63, 112) * x(112)
x(63) = x(63) - temp

temp = M(62, 104) * x(104)
temp = temp + M(62, 107) * x(107)
temp = temp + M(62, 111) * x(111)
temp = temp + M(62, 112) * x(112)
x(62) = x(62) - temp

temp = M(61, 99) * x(99)
temp = temp + M(61, 104) * x(104)
temp = temp + M(61, 109) * x(109)
temp = temp + M(61, 112) * x(112)
x(61) = x(61) - temp

temp = M(60, 102) * x(102)
temp = temp + M(60, 103) * x(103)
temp = temp + M(60, 104) * x(104)
temp = temp + M(60, 105) * x(105)
x(60) = x(60) - temp

temp = M(59, 102) * x(102)
temp = temp + M(59, 103) * x(103)
temp = temp + M(59, 104) * x(104)
temp = temp + M(59, 105) * x(105)
x(59) = x(59) - temp

temp = M(58, 102) * x(102)
temp = temp + M(58, 103) * x(103)
temp = temp + M(58, 104) * x(104)
temp = temp + M(58, 105) * x(105)
x(58) = x(58) - temp

temp = M(57, 96) * x(96)
temp = temp + M(57, 102) * x(102)
temp = temp + M(57, 104) * x(104)
temp = temp + M(57, 108) * x(108)
x(57) = x(57) - temp

temp = M(56, 80) * x(80)
temp = temp + M(56, 101) * x(101)
temp = temp + M(56, 104) * x(104)
temp = temp + M(56, 105) * x(105)
temp = temp + M(56, 110) * x(110)
temp = temp + M(56, 112) * x(112)
x(56) = x(56) - temp

temp = M(55, 103) * x(103)
temp = temp + M(55, 104) * x(104)
temp = temp + M(55, 112) * x(112)
x(55) = x(55) - temp

temp = M(54, 86) * x(86)
temp = temp + M(54, 104) * x(104)
temp = temp + M(54, 108) * x(108)
x(54) = x(54) - temp

temp = M(53, 104) * x(104)
temp = temp + M(53, 108) * x(108)
temp = temp + M(53, 112) * x(112)
x(53) = x(53) - temp

temp = M(52, 100) * x(100)
temp = temp + M(52, 101) * x(101)
temp = temp + M(52, 104) * x(104)
temp = temp + M(52, 110) * x(110)
temp = temp + M(52, 112) * x(112)
x(52) = x(52) - temp

temp = M(51, 101) * x(101)
temp = temp + M(51, 110) * x(110)
temp = temp + M(51, 112) * x(112)
x(51) = x(51) - temp

temp = M(50, 104) * x(104)
temp = temp + M(50, 108) * x(108)
temp = temp + M(50, 110) * x(110)
x(50) = x(50) - temp

temp = M(49, 104) * x(104)
temp = temp + M(49, 107) * x(107)
temp = temp + M(49, 108) * x(108)
x(49) = x(49) - temp

temp = M(48, 95) * x(95)
temp = temp + M(48, 100) * x(100)
temp = temp + M(48, 111) * x(111)
x(48) = x(48) - temp

temp = M(47, 60) * x(60)
temp = temp + M(47, 67) * x(67)
temp = temp + M(47, 102) * x(102)
x(47) = x(47) - temp

temp = M(46, 108) * x(108)
temp = temp + M(46, 111) * x(111)
x(46) = x(46) - temp

temp = M(45, 82) * x(82)
temp = temp + M(45, 102) * x(102)
x(45) = x(45) - temp

temp = M(44, 95) * x(95)
temp = temp + M(44, 112) * x(112)
x(44) = x(44) - temp

temp = M(43, 95) * x(95)
temp = temp + M(43, 112) * x(112)
x(43) = x(43) - temp

temp = M(42, 57) * x(57)
temp = temp + M(42, 104) * x(104)
x(42) = x(42) - temp

temp = M(41, 100) * x(100)
temp = temp + M(41, 104) * x(104)
x(41) = x(41) - temp

temp = M(40, 57) * x(57)
temp = temp + M(40, 104) * x(104)
x(40) = x(40) - temp

temp = M(39, 102) * x(102)
temp = temp + M(39, 108) * x(108)
x(39) = x(39) - temp

temp = M(38, 104) * x(104)
temp = temp + M(38, 110) * x(110)
x(38) = x(38) - temp

temp = M(37, 69) * x(69)
temp = temp + M(37, 104) * x(104)
x(37) = x(37) - temp

temp = M(36, 68) * x(68)
temp = temp + M(36, 71) * x(71)
temp = temp + M(36, 112) * x(112)
x(36) = x(36) - temp

temp = M(35, 68) * x(68)
temp = temp + M(35, 71) * x(71)
temp = temp + M(35, 112) * x(112)
x(35) = x(35) - temp

temp = M(34, 68) * x(68)
temp = temp + M(34, 71) * x(71)
temp = temp + M(34, 112) * x(112)
x(34) = x(34) - temp

temp = M(33, 104) * x(104)
x(33) = x(33) - temp

temp = M(32, 104) * x(104)
x(32) = x(32) - temp

temp = M(31, 104) * x(104)
x(31) = x(31) - temp

temp = M(30, 104) * x(104)
x(30) = x(30) - temp

temp = M(29, 104) * x(104)
x(29) = x(29) - temp

temp = M(28, 104) * x(104)
x(28) = x(28) - temp

temp = M(27, 104) * x(104)
x(27) = x(27) - temp

temp = M(26, 104) * x(104)
x(26) = x(26) - temp

temp = M(25, 104) * x(104)
x(25) = x(25) - temp

temp = M(24, 104) * x(104)
x(24) = x(24) - temp

temp = M(23, 104) * x(104)
x(23) = x(23) - temp

temp = M(22, 68) * x(68)
x(22) = x(22) - temp

temp = M(21, 68) * x(68)
x(21) = x(21) - temp

temp = M(20, 104) * x(104)
x(20) = x(20) - temp

temp = M(19, 104) * x(104)
x(19) = x(19) - temp

temp = M(18, 104) * x(104)
x(18) = x(18) - temp

temp = M(17, 104) * x(104)
x(17) = x(17) - temp

temp = M(16, 104) * x(104)
x(16) = x(16) - temp

temp = M(15, 104) * x(104)
x(15) = x(15) - temp

temp = M(14, 104) * x(104)
x(14) = x(14) - temp

temp = M(13, 104) * x(104)
x(13) = x(13) - temp

temp = M(12, 104) * x(104)
x(12) = x(12) - temp

temp = M(11, 104) * x(104)
x(11) = x(11) - temp

temp = M(10, 104) * x(104)
x(10) = x(10) - temp

temp = M(9, 104) * x(104)
x(9) = x(9) - temp

temp = M(8, 104) * x(104)
x(8) = x(8) - temp

temp = M(7, 104) * x(104)
x(7) = x(7) - temp

temp = M(6, 104) * x(104)
x(6) = x(6) - temp

temp = M(5, 104) * x(104)
x(5) = x(5) - temp

temp = M(4, 105) * x(105)
x(4) = x(4) - temp


END
