!------------------------------------------------------------------------
!     This file was automatically generated by SPACK.
!------------------------------------------------------------------------

subroutine ssh_dimensions                        ( &
    Ns, Nr, Nr_photolysis)

!------------------------------------------------------------------------
!
  integer Ns, Nr, Nr_photolysis

  Ns =   112
  Nr =   231
  Nr_photolysis =    24

return
end

